# Generated by Django 5.2.7 on 2025-11-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='user@cloud.com', max_length=100)),
                ('mob', models.CharField(max_length=10, unique=True)),
                ('profile_pic', models.URLField(default='empty')),
                ('password', models.CharField(default='password', max_length=255)),
            ],
        ),
    ]
