# Generated by Django 5.2.7 on 2025-11-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_cloudtable_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudtable',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
    ]
